### ISSUE TITLE
Replay parameters

### ISSUE THREAD

**Issue by maxencefaldor** [danijar/dreamerv3#129]
In the appendix you mention that prioritized replay improves the performance of Dreamer.

Could you please provide further clarification on the replay parameters used in the configuration?
```
replay:
  size: 5e6
  online: True
  fracs: {uniform: 1.0, priority: 0.0, recency: 0.0}
  prio: {exponent: 0.8, maxfrac: 0.5, initial: inf, zero_on_sample: True}
  priosignal: model
  recexp: 1.0
  chunksize: 1024
  save_wait: False
```

Thank you!
