### ISSUE TITLE
The 12M model sizes doesn't align with the paper

### ISSUE THREAD

**Issue by LYK-love** [danijar/dreamerv3#131]
Hello, I found the model sizes in `config.yaml` are like
```yaml
size12m: &size12m
  dyn.rssm: {deter: 2048, hidden: 256, classes: 16}
  .*\.depth: 16
  .*\.units: 256

size25m: &size25m
  dyn.rssm: {deter: 3072, hidden: 384, classes: 24}
  .*\.depth: 24
  .*\.units: 384

size50m: &size50m
  dyn.rssm: {deter: 4096, hidden: 512, classes: 32}
  .*\.depth: 32
  .*\.units: 512

size100m: &size100m
  dyn.rssm: {deter: 6144, hidden: 768, classes: 48}
  .*\.depth: 48
  .*\.units: 768

size200m: &size200m
  dyn.rssm: {deter: 8192, hidden: 1024, classes: 64}
  .*\.depth: 64
  .*\.units: 1024
```

For the model size=12M, I think the `deter`and `hidden` should be 1024 and 256 according to the DreamerV3 paper:
<img width="658" alt="image" src="https://github.com/danijar/dreamerv3/assets/74082944/5f6bf7f9-d89b-4316-9ab7-fbd3bbc91933">
