### ISSUE TITLE
RESOURCE_EXHAUSTED error after multiple hours of training

### ISSUE THREAD

**Issue by Max-We** [danijar/dreamerv3#152]
### Problem

I'm running the `main.py` training script inside the docker-container from the Dockerfile and after a few hours of training (~12h, ~800k timesteps) on an RTX 3090 I get the following error:

```
1778 ValueError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 14296180248 bytes.
```

### Setup

The system metrics look stable and don't show any signs of running out of vRAM / RAM:

![Screenshot from 2024-09-03 21-41-00](https://github.com/user-attachments/assets/57cc1b17-8697-43f2-b623-4146fac2a74c)
![Screenshot from 2024-09-03 21-41-08](https://github.com/user-attachments/assets/c7268ae1-ee04-477d-b422-648d71820f10)

The command I'm using to start the training is the following (`tetris` is a custom environment I implemented, and it uses a config comparable to Atari).

```
/app/dreamerv3/main.py --logdir /root/logdir/tetris-dreamer/{timestamp} --configs tetris size200m
```

```
tetris:
  task: tetris_rgb
  wandb_project: 'dreamer-tetris'
  (enc|dec).simple.minres: 6
  env.tetris.size: [96, 96]
  run:
    steps: 200e6
    train_ratio: 64
  enc.spaces: 'image'
  dec.spaces: 'image'
```

### Questions

It looks like this error is due to the GPU running out of memory. The DreamerV3 paper mentions that training was conducted on an A100, but it's unclear how much vRAM (40 / 80GB version?) / RAM is required to train the model. I suspect the 24GB RTX 3090 would not be enough for the 200M model, but it could also be an error in the implementation. Are there heuristics to get a rough estimate for the different model sizes / batch sizes before starting the training to avoid failure after multiple hours?

Thank you for maintaining the project!
